### ISSUE TITLE
Add support for CSV export

### ISSUE THREAD

**Issue by efa** [alus-it/AirspaceConverter#105]
add an issue to keep track of the request.
CSV format is the one used by LittleNavMap, that is about this one:
Type,Name,Ident,Lat,Lon,Elev,Label,Desc,Country,Range,Source/ModificationTime

**Comment by alus-** [comment]
This can be a useful feature for some user.
CSV files can be also used by many other software including the well known MS Excel...

**Comment by efa** [comment]
there was an error in fields list in first post, the right one is this:
Type,Name,Ident,Lat,Lon,Elev,Decl,Label,Desc,Country,Range,ModificationTime,SourceFile

Notes:
LNM fill the Declination field on export, ignore it when importing
LNM fill the SourceFile field on export, ignore it when importing and take note internally of real source file
Type can be: Airport, Airstrip, Bookmark, DME, Helipad, NDB, TACAN, VOR, VORDME, VORTAC, VRP, Waypoint

**Comment by efa** [comment]
the support of CSV in not complete but work. It miss:
1) exporting some fields for some kind of points that has them:
a) Airports/Airfields: Direction,Length,Frequency
b) NDB/VOR: Frequency
also if LNM can not import them (to check)
2) importing of CSV files

**Comment by efa** [comment]
poin 1) done in 2nd pull:
https://github.com/alus-it/AirspaceConverter/pull/124
still miss importing CSV files

**Comment by alus-** [comment]
The CSV import will be done in another issue. This (CSV output only) we can consider as done for the upcoming release 0.3.7.
