### ISSUE TITLE
Runtime path do not look for directory where executable is

### ISSUE THREAD

**Issue by efa** [alus-it/AirspaceConverter#119]
~/c/AirspaceConverter0.3.7$ tree
...
├── build.sh
├── clean.sh
...
├── debianize.sh
├── install.sh
├── LICENSE
├── macOS
...
├── Makefile
├── README.md
├── Release
│   ├── Airfield.o
│   ├── airspaceconverter
│   ├── AirspaceConverter.o
│   ├── Airspace.o
│   ├── CSV.o
│   ├── Geometry.o
│   ├── KML.o
│   ├── libairspaceconverter.so
│   ├── OpenAIP.o
│   ├── OpenAir.o
│   ├── Polish.o
│   ├── RasterMap.o
│   ├── SeeYou.o
│   └── Waypoint.o
├── src
...
├── test
...
├── uninstall.sh
└── VisualStudio
...

~/c/AirspaceConverter0.3.7$ Release/airspaceconverter 
Release/airspaceconverter: error while loading shared libraries: libairspaceconverter.so: cannot open shared object file: No such file or directory

'libairspaceconverter.so' is in executable directory but not found

**Comment by efa** [comment]
runtime path look for current directory only

**Comment by efa** [comment]
This can be closed with:
https://github.com/alus-it/AirspaceConverter/pull/125

**Comment by efa** [comment]
efa@08i7-2500:~/c/AirspaceConverter0.3.7/Release$ chrpath -l airspaceconverter
airspaceconverter: RUNPATH=$ORIGIN

**Comment by efa** [comment]
the 'build.sh' script generate those files:
Release/airspaceconverter
Release/libairspaceconverter.so
buildQt/airspaceconverter-gui

The CLI command 'airspaceconverter' should always find the shared object as it is in its directory, and now RUNPATH include $ORIGIN that mean "executable directory". To check it please try run:
$ chrpath -l airspaceconverter

The GUI command 'airspaceconverter-gui' cannot find the shared object as it is in Release directory, this is expected.
Note: Having another (maybe old) installation of the .so in /usr/lib is not recommended as version mismatch will generate trouble.
Instead copying 'airspaceconverter-gui' there (or copy 'libairspaceconverter.so' to buildQt) should work.

Anyway just build executable and library are not intended to be run from build dir, should be installed with 'sudo make install' or 'install.sh' as you pointed out, but require root.

**Comment by alus-** [comment]
> Maybe we can add a last step to 'build.sh' that move 'airspaceconverter-gui' to /Release, this to avoid other trouble
Done!

**Comment by efa** [comment]
well done, thank you
