### ISSUE TITLE
AirspaceConverter creates invalid KMZ

### ISSUE THREAD

**Issue by alus-** [alus-it/AirspaceConverter#122]
Issue reported by: Nico Mak, nico_extra@yahoo.com

I am looking for a way to convert CUP files to Google Earth with useful icons (e.g. not the same icon for an airport, off field landing, and mountain top) and thought I'd give your program a try.  I tried converting the attached CUP file.  When I loaded the resulting KMZ into Google Earth I got the Parse Error on line 5979 shown in the attached screen capture. (I also got a bunch of warnings about invalid runway lengths during the conversion but I don't really care about that, at this point I just want to find out if the program does a useful job of displaying icons as described above).

![1599171289596blob](https://user-images.githubusercontent.com/3354240/93012785-3a9c0800-f5a3-11ea-8c7d-bd1319ff08f6.jpg)

[SW2020 v3 2KA.zip](https://github.com/alus-it/AirspaceConverter/files/5213734/SW2020.v3.2KA.zip)

**Comment by alus-** [comment]
I see two solvable problems here:
- An '&' ampersand in the description is not accepted inside a tag
- Runway lengths expressed feet are not accepted when reading CUP files

**Comment by efa** [comment]
the file format specification of CUP by Naviter SeeYou about lenghts say:

9 Runway Length
Number with unit representing length of the runway. Only used with Waypoint style types 2, 3, 4
and 5. The unit can be either "m" for meters "nm" for nautical miles "ml" for statute miles. Decimal
separator must be a point.
Example: 540.3m

so feet is not allowed. Where did you get the CUP file from?

**Comment by alus-** [comment]
We can support also feet anyway quite easy to do.

**Comment by alus-** [comment]
Fixed!
