### ISSUE TITLE
CUP field 10 Airport frequency digits

### ISSUE THREAD

**Issue by efa** [alus-it/AirspaceConverter#129]
The CUP file format specification say frequency must have 3 decimal digits

**Comment by alus-** [comment]
So always 3 digits for radio frequencies?
For NDB frequencies in kHz I used only one digit

**Comment by alus-** [comment]
As discussed this is not necessary.
SeeYou is anyway not strictly validating his own CUP format.

We keep doing our own way:
- Airband radio in MHz: 3 decimals
- VOR in MHz: 2 decimals
- NDB in kHz: 1 decimal
