### ISSUE TITLE
Add support for CSV import

### ISSUE THREAD

**Issue by alus-** [alus-it/AirspaceConverter#130]
CSV format is the one used by LittleNavMap, that is about this one:
Type,Name,Ident,Lat,Lon,Elev,Label,Desc,Country,Range,Source/ModificationTime

The export was already done, this issue is about the ability to import CSV files as waypoints input.

**Comment by efa** [comment]
CSV are comma separated files, with lines like the following template:
Type,Name,Ident,Lat,Lon,Elev,Decl,Label,Desc,Country,Range,ModificationTime,SourceFile
Type can be at least: Airport, Airstrip, Bookmark, DME, Helipad, NDB, TACAN, VOR, VORDME, VORTAC, VRP, Waypoint
LNM2.4.5:Airport,Airstrip,Bookmark,Cabin,Closed,DME,Error,Flag,Helipad,Lighthouse,Location,Logbook,Marker,Mountain,NDB,Obstacle,POI,Pin,Seaport,TACAN,Unknown,VOR,VORDME,VORTAC,VRP,Waypoint
LNM2.6 automatically detected comment line:
"Type,Name,Ident,Latitude,Longitude,Elevation,Magnetic Declination,Tags,Description,Region,Visible From,Last Edit,Import Filename"
# Note: Lat/Lon must be in DDD.MMMMMM format, Elev is in feet and unit must be omitted
# Note: Elevation is always feet and distances are always nautical miles
# Note: LNM fill the Declination field on export, not used when importing
# Note: LNM fill the SourceFile field on export, ignore it when importing and take note of real source file

**Comment by efa** [comment]
initial import CSV support is in https://github.com/alus-it/AirspaceConverter/pull/142
