### ISSUE TITLE
Build DEB packges for Ubuntu

### ISSUE THREAD

**Issue by alus-** [alus-it/AirspaceConverter#46]
Adapt the debianize.sh script to produce the DEB packages also for Ubuntu 16.04 considering the proper versions of the dependencies.

**Comment by efa** [comment]
ecco i pacchetti, a valle dei tuoi ultimi commit:

[airspaceconverter_0.2.6-ubn16.04_amd64.deb.zip](https://github.com/alus-it/AirspaceConverter/files/1525194/airspaceconverter_0.2.6-ubn16.04_amd64.deb.zip)
[airspaceconverter-gui_0.2.6-ubn16.04_amd64.deb.zip](https://github.com/alus-it/AirspaceConverter/files/1525195/airspaceconverter-gui_0.2.6-ubn16.04_amd64.deb.zip)

purtroppo github supporta solo gli archivi .zip

**Comment by alus-** [comment]
Perfetto, dunque possiamo considerare questo issue completato.

**Comment by efa** [comment]
here the packages generated, tested and zipped. Then I run:
$ zip -T <package>.deb.zip
to be sure are compressed right.

[airspaceconverter_0.2.6-ubn16.04_amd64.deb.zip](https://github.com/alus-it/AirspaceConverter/files/1526984/airspaceconverter_0.2.6-ubn16.04_amd64.deb.zip)
[airspaceconverter-gui_0.2.6-ubn16.04_amd64.deb.zip](https://github.com/alus-it/AirspaceConverter/files/1526985/airspaceconverter-gui_0.2.6-ubn16.04_amd64.deb.zip)
