### ISSUE TITLE
Show supported files in input directory selection dialog box

### ISSUE THREAD

**Issue by efa** [alus-it/AirspaceConverter#55]

**Comment by alus-** [comment]
Not sure how to do this, maybe re-using the open file dialog, so showing the files, to select a directory. Anyway the user can already select multiple files using the normal open file dialog.

**Comment by alus-** [comment]
The user can already select multiple files using the normal open file dialog. The files shown are already filtered on the known extensions for input files. For output file, changing the type will also make to converter to switch to the other desired format.
