### ISSUE TITLE
kml output -- SchemaData w/o schemaUrl?

### ISSUE THREAD

**Issue by think-nice-things** [alus-it/AirspaceConverter#96]
Hi,

when converting aip airport data to kml airspaceconverter generates kml with SchemaData w/o a schemaUrl attribute. **Is this conformant with the the kml specification?** As far as I understand the specification, SchemaData has to relate to a schemaUrl.

I discovered this while trying to read the generated kml with python's fastkml module. There fastkml.kml.KML.etree_elements generates errors when working on kml data generated by airspaceconverter.

**Comment by alus-** [comment]
Hi!
first of all: thank you for your interest in this project and thank for reporting this issue.

So if I understand correctly the generated KML is not properly conformant to the used [KML schema](http://www.opengis.net/kml/2.2) especially concerning waypoints.

Can you tell me a little more about those errors you get?

**Comment by alus-** [comment]
Predefined `Schema`'s for airspace and waypoint `SchemaData` elements has been defined so now every `SchemaData` will be related to a schema url within the same KML file.
